export type IpcResult<T> = { ok: true; data: T } | { ok: false; error: string };

export const IPC_CHANNELS = [
  'vault:create',
  'vault:open',
  'vault:status',
  'vault:saved-key-status',
  'vault:unlock-saved',
  'vault:forget-saved',
  'events:create',
  'encounters:create',
  'inbox:scan',
  'inbox:list',
  'inbox:confirm',
  'inbox:reject',
  'verify:run',
  'citation:make',
  'purge:subject',
  'backup:export',
  'backup:pick',
  'backup:restore',
  'archive:events',
  'archive:encounters',
  'archive:artifacts',
  'archive:detail',
  'evidence:list',
  'memos:confirm',
  'research:load',
  'research:memo-create',
  'research:memo-code',
  'journals:build',
  'participants:upsert',
  'participants:set-real-name',
  'consents:record',
  'consents:withdraw',
  'settings:get',
  'settings:set',
  'time:sync',
  'mock:load',
  'mock:clear',
  'mock:status',
] as const;

export type IpcChannel = (typeof IPC_CHANNELS)[number];
